[package]
name = "renderer_wgpu_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
env_logger = "0.10"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.56"
wgpu = { version = "27.0.1", features = ["webgl"] }

[dependencies.web-sys]
version = "0.3"
features = ["console", "WebGl2RenderingContext"]