#define BLENDING_MODE_NORMAL 0
#define BLENDING_MODE_DISSOLVE 1
#define BLENDING_MODE_COLOR_ERASE 2
#define BLENDING_MODE_ERASE 3
#define BLENDING_MODE_MERGE 4
#define BLENDING_MODE_SPLIT 5

#define BLENDING_MODE_LIGHTEN_ONLY 6
#define BLENDING_MODE_LUMA_LIGHTEN_ONLY 7
#define BLENDING_MODE_SCREEN 8
#define BLENDING_MODE_DODGE 9

#define BLENDING_MODE_ADDITION 10
#define BLENDING_MODE_DARKEN_ONLY 11
#define BLENDING_MODE_LUMA_DARKEN_ONLY 12
#define BLENDING_MODE_MULTIPLY 13
#define BLENDING_MODE_BURN 14
#define BLENDING_MODE_LINEAR_BURN 15

#define BLENDING_MODE_OVERLAY 16
#define BLENDING_MODE_SOFT_LIGHT 17
#define BLENDING_MODE_HARD_LIGHT 18
#define BLENDING_MODE_VIVID_LIGHT 19
#define BLENDING_MODE_PIN_LIGHT 20
#define BLENDING_MODE_LINEAR_LIGHT 21
#define BLENDING_MODE_HARD_MIX 22

#define BLENDING_MODE_DIFFERENCE 23
#define BLENDING_MODE_EXCLUSION 24
#define BLENDING_MODE_SUBTRACT 25
#define BLENDING_MODE_GRAIN_EXTRACT 26
#define BLENDING_MODE_GRAIN_MERGE 27
#define BLENDING_MODE_DIVIDE 28

#define BLENDING_MODE_HUE 29
#define BLENDING_MODE_COLOR 30
#define BLENDING_MODE_VALUE 31