const { webfont } = require('webfont');
const fs = require('fs');
const path = require('path');

const cssHeader = `/*
    THIS FILE IS AUTO-GENERATED BY scripts/webfont.js
    DO NOT MAKE MANUAL CHANGES TO THIS FILE
*/\n\n`;

webfont({
    template: path.join(__dirname, '../src/assets/images/icons/template.css.njk'),
    files: path.join(__dirname, '../src/assets/images/icons/*.svg'),
    templateFontPath: '../fonts/OpenGraphicaIcons',
    fontName: 'OpenGraphicaIcons',
}).then((result) => {
    fs.writeFileSync(path.join(__dirname, '../src/assets/fonts/OpenGraphicaIcons/OpenGraphicaIcons.eot'), result.eot);
    fs.writeFileSync(path.join(__dirname, '../src/assets/fonts/OpenGraphicaIcons/OpenGraphicaIcons.svg'), result.svg);
    fs.writeFileSync(path.join(__dirname, '../src/assets/fonts/OpenGraphicaIcons/OpenGraphicaIcons.ttf'), result.ttf);
    fs.writeFileSync(path.join(__dirname, '../src/assets/fonts/OpenGraphicaIcons/OpenGraphicaIcons.woff'), result.woff);
    fs.writeFileSync(path.join(__dirname, '../src/assets/fonts/OpenGraphicaIcons/OpenGraphicaIcons.woff2'), result.woff2);
    fs.writeFileSync(path.join(__dirname, '../src/css/opengraphica/webfont.scss'), cssHeader + result.template);
})
.catch((error) => {
    throw error;
});